os:
  - linux
dist: trusty
sudo: required
language: c

script:
  - curl https://api.github.com/repos/frangarcj/buildscripts/releases  | grep browser_download_url | grep linux | head -n 1 | cut -d '"' -f 4 | xargs wget
  - tar xjf *.tar.bz2
  - export VITASDK=$PWD/vitasdk
  - export PATH=$VITASDK/bin:$PATH
  - mkdir build && cd build
  - cmake ../
  - make
  - cd ..
  - mkdir -p output/lib
  - mkdir -p output/include
  - cp taihen.h output/include
  - cp build/taihen-libs/*.a output/lib/
  - tar -C output -zcvf $PWD/taihen.tar.gz  .
env:
 global:
  - TOP=$PWD
  - PREFIX=$TOP/dist
before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_BRANCH-0.1-v$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER - $TRAVIS_OS_NAME"
  - git push -q https://$TAGPERM@github.com/frangarcj/taihen --tags
deploy:
  provider: releases
  api_key: $OAUTH 
  file: 
     - "build/taihen.skprx"
     - "taihen.tar.gz"
  skip_cleanup: true
  on:
    tags: false
    all_branches: true

branches:
  except:
    - /^*-v[0-9]/
